# Pretrain a Llama2-like model on SkyPilot

name: train

resources:
  accelerators: V100:1

num_nodes: 1

envs:
  HF_TOKEN: ""
  WANDB_API_KEY: ""
  GIT_USERNAME: ""
  GIT_EMAIL: ""

  CONFIG: "softmax1-15m"

workdir: .

setup: |
  conda activate chatbot
  if [ $? -ne 0 ]; then
    conda create -n llama python=3.9 -y
    conda activate llama
  fi

  git config --global credential.helper store
  git config --global user.name $GIT_USERNAME
  git config --global user.email $GIT_EMAIL
  sudo apt install git-lfs
  git lfs install

  cd ~/sky_workdir
  pip install -r requirements.txt

  python tinystories.py download
  python tinystories.py pretokenize

run: |
  set -e  # Exit if any command failed.
  conda activate llama
  cd ~/sky_workdir

  python train.py config/$CONFIG.py
